# Site settings
title: Kekal Maju
description: Kekal Maju
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kekalmaju.github.io" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%b %-d, %Y"
email: kekalmaju.my@gmail.com
google_analytics: 
address: B3-1-12, Blok B3, Aras 1, Canaan Square Business Hub, Jalan Stutong Baru, 93250 Kuching. Sarawak. Malaysia.
address_link: https://goo.gl/maps/nhNTUTs2r6KM3pNz7

# Defaults
defaults:
  - scope: 
      path: ""
    values:
      layout: "default"

# Sass doesn't work with @use
sass:
  silence_deprecations: ['import']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - "*.code-workspace"
