# Site settings
title: Kekal Maju
description: Kekal Maju
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kekalmaju.github.io" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%b %-d, %Y"
email: kekalmaju.my@gmail.com
google_analytics: 
address: No. 355, Tingkat 1, Tabuan Laru Commercial Centre, Jalan Setia Raja, 93350 Kuching. Sarawak. Malaysia.

# Defaults
defaults:
  - scope: 
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - "*.code-workspace"
